version: "3"

services:
  expo:
    container_name: messenkrypt-expo
    restart: always
    build: .
    volumes:
      - "./:/usr/src/app"
      - "/usr/src/app/node_modules"
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
      - "19006:19006" #WEB Mode
    environment:
      - EXPO_PACKAGER_HOSTNAME=192.168.0.13
